Repository Maria2811-code/Project-3Class15_3-HYF_website, pull requests merged in 2021-04, with the labels that each got.

#9 add constraints
  Planning/Constraints.md
Labels: documentation, week-2

#22 Hotfix, changing folders
  Planning/backlog.md
Labels: documentation, week-2

#24 Hajir-pro.md
  Planning/Retrospective.md
Labels: week-2

#27 Resolve #16
  index.html
  style.css
Labels: HTML, week 3

#32 Our partners
  Planning/backlog.md
  partners-francis/css/newstyle.css
  partners-francis/newindex.html
  partners-francis/nuhack/1.png
  partners-francis/nuhack/10.png
  partners-francis/nuhack/11.png
  partners-francis/nuhack/12.png
  partners-francis/nuhack/2.png
  partners-francis/nuhack/3.png
  partners-francis/nuhack/4.png
  partners-francis/nuhack/5.png
  partners-francis/nuhack/6.png
  partners-francis/nuhack/7.png
  partners-francis/nuhack/8.png
  partners-francis/nuhack/9.png
Labels: CSS, HTML
